language: ruby
rvm:
  - 1.9.3
addons:
  apt:
    packages:
      - build-essential
      - libsdl2-dev
      - libsdl2-ttf-dev
      - libpango1.0-dev
      - libgl1-mesa-dev
      - libfreeimage-dev
      - libopenal-dev
      - libsndfile-dev

before_install:
  - git submodule update --init
  - gem install opal
  - gem install gosu
install:
  - ruby build.rb web-craftyjs
  - ruby build.rb desktop-gosu
