language: ruby
rvm:
  - 1.9.3
before_install:
  - git submodule update --init --recursive
  - gem install opal
  - gem install ocra
install:
  - ruby build.rb web-craftyjs
  - ruby build.rb desktop-gosu
