language: ruby
rvm:
  - 1.9.3
before_install:
  before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential freeglut3-dev libfreeimage-dev libgl1-mesa-dev libopenal-dev libpango1.0-dev libsdl-ttf2.0-dev libsndfile-dev libxinerama-dev
install:
  - git submodule update --init
  - gem install opal
  - gem install gosu
  - ruby build.rb web-craftyjs
  - ruby build.rb desktop-gosu
