# http://lint.travis-ci.org/
language: ruby
rvm:
  - 1.9.3
  # Use sed to replace the SSH URL with the public URL, then initialize submodules
  # This allows us to use git@github.com locally, but https:// for builds.
before_install:
  - git submodule update --init --recursive
  - gem install opal
  - gem install ruboto
install:
  - ruby build.rb web-craftyjs
  - ruby build.rb android-libgdx
